[package]
name = "codeforces"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "96a"
path = "src/bin/96a.rs"

[[bin]]
name = "4a"
path = "src/bin/4a.rs"

[[bin]]
name = "71a"
path = "src/bin/71a.rs"

[[bin]]
name = "231a"
path = "src/bin/231a.rs"

[[bin]]
name = "282a"
path = "src/bin/282a.rs"
